name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
runs:
  using: composite
  steps:
    - uses: ./swift/actions/setup-env
    - uses: ./swift/actions/share-extractor-pack
    - name: Build Swift extractor
      shell: bash
      run: |
        bazel run //swift:create-extractor-pack
    # running all small tests here to avoid spinning another runner and redoing bazel analysis
    - name: Run unit tests
      shell: bash
      run: |
        bazel test --test_filter=small --build_tests_only //swift/...
