name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
runs:
  using: composite
  steps:
    - uses: ./swift/actions/env-setup
    - uses: ./swift/actions/share-extractor-pack
    - name: Build Swift extractor
      shell: bash
      run: |
        bazel run //swift:create-extractor-pack
