name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
runs:
  using: composite
  steps:
    - uses: ./swift/actions/env-setup
    - uses: ./swift/actions/share-extractor-pack
    - uses: ./swift/actions/share-extractor-pack
    - name: Test qltest.sh
      shell: bash
      run: |
        bazel test //swift/tools/test/qltest
    - uses: ./.github/actions/fetch-codeql
    - name: Run QL tests
      shell: bash
      run: |
        codeql test run \
          --threads=0 \
          --ram 5000 \
          --search-path "${{ github.workspace }}/swift/extractor-pack" \
          --check-databases \
          --check-unused-labels \
          --check-repeated-labels \
          --check-redefined-labels \
          --check-use-before-definition \
          ql/test
      env:
        GITHUB_TOKEN: ${{ github.token }}
