[package]
name = "yeast"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tree-sitter = "0.20.10"

tree-sitter-ruby = "0.20.0"
tree-sitter-python = "0.20.4"
