name: "Compile all queries using the latest stable CodeQL CLI"

on:
  push:
    branches: [main] # makes sure the cache gets populated
  pull_request:
    branches:
      - main
      - "rc/*"

jobs:
  compile-queries:
    runs-on: ubuntu-latest-xl

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # calculate the merge-base with main, in a way that works both on PRs and pushes to main. 
      - name: Calculate merge-base
        if: ${{ github.event_name == 'pull_request' }}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          MERGE_BASE=$(git merge-base --fork-point origin/$BASE_BRANCH)
          echo "merge-base=$MERGE_BASE" >> $GITHUB_ENV
      - name: Read CodeQL query compilation - PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/cache@v3
        with:
          path: '*/ql/src/.cache'
          key: codeql-compile-pr-${{ github.sha }} # deliberately not using the `compile-compile-main` keys here.
          restore-keys: |
            codeql-compile-main-${{ env.merge-base }}
            codeql-compile-main-
      - name: Fill CodeQL query compilation cache - main
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/cache@v3
        with:
          path: '*/ql/src/.cache'
          key: codeql-compile-main-${{ github.sha }} # just fill on main
          restore-keys: | # restore from another random commit, to speed up compilation.
            codeql-compile-main- 
      - name: Setup CodeQL
        uses: ./.github/actions/fetch-codeql
        with:
          channel: 'release'
      - name: check formatting
        run: codeql query format */ql/{src,lib,test}/**/*.{qll,ql} --check-only
      - name: compile queries - check-only
        # run with --check-only if running in a PR (github.sha != main)
        if : ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: codeql query compile -j0 */ql/src --keep-going --warnings=error --check-only
      - name: compile queries - full
        # do full compile if running on main - this populates the cache
        if : ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: codeql query compile -j0 */ql/src --keep-going --warnings=error