name: Build framework coverage timeseries reports

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone self (github/codeql)
      uses: actions/checkout@v2
      with:
        path: script
    - name: Clone self (github/codeql) for analysis
      uses: actions/checkout@v2
      with:
        path: codeqlModels
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download CodeQL CLI
      uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
      with:
        repo: "github/codeql-cli-binaries"
        version: "latest"
        file: "codeql-linux64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unzip CodeQL CLI
      run: unzip -d codeql-cli codeql-linux64.zip
    - name: Build modeled package list
      run: |
        CLI=$(realpath "codeql-cli/codeql")
        echo $CLI
        PATH="$PATH:$CLI" python script/misc/scripts/library-coverage/generate-timeseries.py codeqlModels
    - name: Upload timeseries CSV
      uses: actions/upload-artifact@v2
      with:
        name: framework-coverage-timeseries
        path: framework-coverage-timeseries-*.csv

