name: Diff generated Models as Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      projects:
        description: "The projects to generate models for"
        required: true
        default: '["netty/netty"]'
  pull_request:
    branches:
      - main
    paths:
      - "java/ql/src/utils/model-generator/**/*.*"

jobs:
  model-diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # large
        # ["google/guava", "spring-projects/spring-framework", "apache/poi"]
        # others
        # ["FasterXML/jackson-core", "FasterXML/jackson-databind", "google/gson", "JodaOrg/joda-time"
        slugs: ${{fromJson(github.event.inputs.projects || '["apache/commons-codec", "apache/commons-io", "apache/commons-beanutils", "apache/commons-logging", "apache/commons-fileupload", "apache/commons-lang", "apache/commons-validator", "apache/commons-csv", "apache/dubbo"]' )}}
    steps:
      - name: Clone self (github/codeql) for baseline
        uses: actions/checkout@v2
        with:
          path: codeql-baseline
          ref: ${{ github.base_ref }}
