name: Query help preview

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    branches:
      - main
      - "rc/*"
    paths:
      - "ruby/**/*.qhelp"

jobs:
  qhelp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
          fetch-depth: 2
      - name: Determine changed files
        id: changes
        run: |
          (git diff --name-only --diff-filter=ACMRT HEAD~1 HEAD | grep '.qhelp$' | grep -v '.inc.qhelp';
           git diff --name-only --diff-filter=ACMRT HEAD~1 HEAD | grep '.inc.qhelp$' | xargs -d '\n' -rn1 basename | xargs -d '\n' -rn1 git grep -l) |
           sort -u > "${{ runner.temp }}/paths.txt"

      - uses: ./.github/actions/fetch-codeql

      - name: QHelp preview
        if: ${{ steps.changes.outputs.qhelp_files }}
        run: |
          ( echo "QHelp previews:";
          cat "${{ runner.temp }}/paths.txt" | while read path; do
            echo "<details> <summary>${path}</summary>"
            echo
            codeql generate query-help --format=markdown "${path}"
            echo "</details>"
          done) | gh pr comment "${{ github.event.pull_request.number }}" -F -
        env:
          GITHUB_TOKEN: ${{ github.token }}
