name: "Swift: Check code generation"

on:
  pull_request:
    paths:
      - "swift/**"
      - .github/workflows/swift-codegen.yml
    branches:
      - main

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fetch-codeql
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Run unit tests
        run: |
          bazel test //swift/codegen/test --test_output=errors
      - name: Check that QL generated code was checked in
        run: |
          bazel run //swift/codegen
          git add swift
          git diff --exit-code --stat HEAD
      - name: Generate C++ files
        run: |
          bazel run //swift/codegen:trapgen -- --cpp-output=$PWD
          bazel run //swift/codegen:cppgen -- --cpp-output=$PWD
      - uses: actions/upload-artifact@v3
        with:
          name: TrapEntries.h
          path: TrapEntries.h
      - uses: actions/upload-artifact@v3
        with:
          name: TrapTags.h
          path: TrapTags.h
      - uses: actions/upload-artifact@v3
        with:
          name: TrapClasses.h
          path: TrapClasses.h
